dataset_path: nlp-waseda/KnowRecall
dataset_name: default
task: "knowrecall_ru"
dataset_kwargs:
  token: True
test_split: ru
output_type: generate_until
doc_to_visual: !function utils.knowrecall_doc_to_visual
doc_to_text: !function utils.knowrecall_doc_to_text
doc_to_target: !function utils.knowrecall_doc_to_target
generation_kwargs:
  max_new_tokens: 16
  temperature: 0
  do_sample: False
metric_list:
  - metric: exact_match
    aggregation: mean
    higher_is_better: true
    ignore_case: true
    ignore_punctuation: true
metadata:
  - version: 0.0

model_specific_generation_kwargs:
  llava:
    image_aspect_ratio: original
