dataset_path: nlp-waseda/KnowRecall
dataset_name: default
task: "knowrecall_es_structured_cot"
dataset_kwargs:
  token: True
test_split: es
output_type: generate_until
doc_to_visual: !function utils.knowrecall_doc_to_visual
doc_to_text: !function utils.knowrecall_doc_to_text
doc_to_target: !function utils.knowrecall_doc_to_target
generation_kwargs:
  max_new_tokens: 512
  temperature: 0.7
  top_p: 0.8
  top_k: 50
  do_sample: True
metric_list:
  - metric: exact_match
    aggregation: mean
    higher_is_better: true
    ignore_case: true
    ignore_punctuation: true
metadata:
  - version: 0.0

model_specific_generation_kwargs:
  llava:
    image_aspect_ratio: original
