dataset_path: neulab/PangeaBench-xgqa
dataset_name: default
dataset_kwargs:
  token: True
task: "xgqa_id"
test_split: id
output_type: generate_until
doc_to_visual: !function utils.xgqa_doc_to_visual
doc_to_text: !function utils.xgqa_doc_to_text
doc_to_target: "answer"
generation_kwargs:
  max_new_tokens: 16
  temperature: 0
  top_p: 1.0
  num_beams: 1
  do_sample: false
metric_list:
  - metric: exact_match
    aggregation: mean
    higher_is_better: true
    ignore_case: true
    ignore_punctuation: true
process_results: !function utils.xgqa_process_result
metadata:
  - version: 0.0
  
model_specific_prompt_kwargs:
  default:
    pre_prompt: ""
    post_prompt: "\nAnswer the question using a single word or phrase in English."
  qwen_vl:
    pre_prompt: ""
    post_prompt: " Answer:"