country_code_to_country_name = {
    "AD": "Andorra",
    "AE": "United Arab Emirates",
    "AF": "Afghanistan",
    "AG": "Antigua and Barbuda",
    "AI": "Anguilla",
    "AL": "Albania",
    "AM": "Armenia",
    "AO": "Angola",
    "AQ": "Antarctica",
    "AR": "Argentina",
    "AS": "American Samoa",
    "AT": "Austria",
    "AU": "Australia",
    "AW": "Aruba",
    "AX": "Åland Islands",
    "AZ": "Azerbaijan",
    "BA": "Bosnia and Herzegovina",
    "BB": "Barbados",
    "BD": "Bangladesh",
    "BE": "Belgium",
    "BF": "Burkina Faso",
    "BG": "Bulgaria",
    "BH": "Bahrain",
    "BI": "Burundi",
    "BJ": "Benin",
    "BL": "Saint Barthélemy",
    "BM": "Bermuda",
    "BN": "Brunei Darussalam",
    "BO": "Bolivia",
    "BQ": "Bonaire, Sint Eustatius and Saba",
    "BR": "Brazil",
    "BS": "Bahamas",
    "BT": "Bhutan",
    "BV": "Bouvet Island",
    "BW": "Botswana",
    "BY": "Belarus",
    "BZ": "Belize",
    "CA": "Canada",
    "CC": "Cocos (Keeling) Islands",
    "CD": "Congo, the Democratic Republic of the",
    "CF": "Central African Republic",
    "CG": "Congo",
    "CH": "Switzerland",
    "CI": "Ivory Coast",
    "CK": "Cook Islands",
    "CL": "Chile",
    "CM": "Cameroon",
    "CN": "China",
    "CO": "Colombia",
    "CR": "Costa Rica",
    "CU": "Cuba",
    "CV": "Cape Verde",
    "CW": "Curaçao",
    "CX": "Christmas Island",
    "CY": "Cyprus",
    "CZ": "Czech Republic",
    "Code": "Name",
    "DE": "Germany",
    "DJ": "Djibouti",
    "DK": "Denmark",
    "DM": "Dominica",
    "DO": "Dominican Republic",
    "DZ": "Algeria",
    "EC": "Ecuador",
    "EE": "Estonia",
    "EG": "Egypt",
    "EH": "Western Sahara",
    "ER": "Eritrea",
    "ES": "Spain",
    "ET": "Ethiopia",
    "FI": "Finland",
    "FJ": "Fiji",
    "FK": "Falkland Islands (Malvinas)",
    "FM": "Micronesia, Federated States of",
    "FO": "Faroe Islands",
    "FR": "France",
    "GA": "Gabon",
    "GB": "United Kingdom",
    "GD": "Grenada",
    "GE": "Georgia",
    "GF": "French Guiana",
    "GG": "Guernsey",
    "GH": "Ghana",
    "GI": "Gibraltar",
    "GL": "Greenland",
    "GM": "Gambia",
    "GN": "Guinea",
    "GP": "Guadeloupe",
    "GQ": "Equatorial Guinea",
    "GR": "Greece",
    "GS": "South Georgia and the South Sandwich Islands",
    "GT": "Guatemala",
    "GU": "Guam",
    "GW": "Guinea-Bissau",
    "GY": "Guyana",
    "HK": "Hong Kong",
    "HM": "Heard Island and McDonald Islands",
    "HN": "Honduras",
    "HR": "Croatia",
    "HT": "Haiti",
    "HU": "Hungary",
    "ID": "Indonesia",
    "IE": "Ireland",
    "IL": "Israel",
    "IM": "Isle of Man",
    "IN": "India",
    "IO": "British Indian Ocean Territory",
    "IQ": "Iraq",
    "IR": "Iran",
    "IS": "Iceland",
    "IT": "Italy",
    "JE": "Jersey",
    "JM": "Jamaica",
    "JO": "Jordan",
    "JP": "Japan",
    "KE": "Kenya",
    "KG": "Kyrgyzstan",
    "KH": "Cambodia",
    "KI": "Kiribati",
    "KM": "Comoros",
    "KN": "Saint Kitts and Nevis",
    "KP": "Korea, Democratic People's Republic of",
    "KR": "South Korea",
    "KW": "Kuwait",
    "KY": "Cayman Islands",
    "KZ": "Kazakhstan",
    "LA": "Laos PDR",
    "LB": "Lebanon",
    "LC": "Saint Lucia",
    "LI": "Liechtenstein",
    "LK": "Sri Lanka",
    "LR": "Liberia",
    "LS": "Lesotho",
    "LT": "Lithuania",
    "LU": "Luxembourg",
    "LV": "Latvia",
    "LY": "Libya",
    "MA": "Morocco",
    "MC": "Monaco",
    "MD": "Moldova, Republic of",
    "ME": "Montenegro",
    "MF": "Saint Martin (French part)",
    "MG": "Madagascar",
    "MH": "Marshall Islands",
    "MK": "Macedonia, the Former Yugoslav Republic of",
    "ML": "Mali",
    "MM": "Myanmar",
    "MN": "Mongolia",
    "MO": "Macao",
    "MP": "Northern Mariana Islands",
    "MQ": "Martinique",
    "MR": "Mauritania",
    "MS": "Montserrat",
    "MT": "Malta",
    "MU": "Mauritius",
    "MV": "Maldives",
    "MW": "Malawi",
    "MX": "Mexico",
    "MY": "Malaysia",
    "MZ": "Mozambique",
    "NA": "Namibia",
    "NC": "New Caledonia",
    "NE": "Niger",
    "NF": "Norfolk Island",
    "NG": "Nigeria",
    "NI": "Nicaragua",
    "NL": "Netherlands",
    "NO": "Norway",
    "NP": "Nepal",
    "NR": "Nauru",
    "NU": "Niue",
    "NZ": "New Zealand",
    "OM": "Oman",
    "PA": "Panama",
    "PE": "Peru",
    "PF": "French Polynesia",
    "PG": "Papua New Guinea",
    "PH": "Philippines",
    "PK": "Pakistan",
    "PL": "Poland",
    "PM": "Saint Pierre and Miquelon",
    "PN": "Pitcairn",
    "PR": "Puerto Rico",
    "PS": "Palestine",
    "PT": "Portugal",
    "PW": "Palau",
    "PY": "Paraguay",
    "QA": "Qatar",
    "RE": "Réunion",
    "RO": "Romania",
    "RS": "Serbia",
    "RU": "Russia",
    "RW": "Rwanda",
    "SA": "Saudi Arabia",
    "SB": "Solomon Islands",
    "SC": "Seychelles",
    "SD": "Sudan",
    "SE": "Sweden",
    "SG": "Singapore",
    "SH": "Saint Helena, Ascension and Tristan da Cunha",
    "SI": "Slovenia",
    "SJ": "Svalbard and Jan Mayen",
    "SK": "Slovakia",
    "SL": "Sierra Leone",
    "SM": "San Marino",
    "SN": "Senegal",
    "SO": "Somalia",
    "SR": "Suriname",
    "SS": "South Sudan",
    "ST": "Sao Tome and Principe",
    "SV": "El Salvador",
    "SX": "Sint Maarten",
    "SY": "Syria",
    "SZ": "Eswatini",
    "TC": "Turks and Caicos Islands",
    "TD": "Chad",
    "TF": "French Southern Territories",
    "TG": "Togo",
    "TH": "Thailand",
    "TJ": "Tajikistan",
    "TK": "Tokelau",
    "TL": "Timor-Leste",
    "TM": "Turkmenistan",
    "TN": "Tunisia",
    "TO": "Tonga",
    "TR": "Turkey",
    "TT": "Trinidad and Tobago",
    "TV": "Tuvalu",
    "TW": "Taiwan",
    "TZ": "Tanzania",
    "UA": "Ukraine",
    "UG": "Uganda",
    "UM": "United States Minor Outlying Islands",
    "US": "United States of America",
    "UY": "Uruguay",
    "UZ": "Uzbekistan",
    "VA": "Holy See (Vatican City State)",
    "VC": "Saint Vincent and the Grenadines",
    "VE": "Venezuela, Bolivarian Republic of",
    "VG": "Virgin Islands, British",
    "VI": "Virgin Islands, U.S.",
    "VN": "Vietnam",
    "VU": "Vanuatu",
    "WF": "Wallis and Futuna",
    "WS": "Samoa",
    "YE": "Yemen",
    "YT": "Mayotte",
    "ZA": "South Africa",
    "ZM": "Zambia",
    "ZW": "Zimbabwe",
    "OTHER": "Other",
}

# 38 languages that Gemini supports
language_code_to_language_name = {
    "ar": "Arabic",
    "bg": "Bulgarian",
    "bn": "Bengali",
    "cs": "Czech",
    "da": "Danish",
    "de": "German",
    "el": "Greek",
    "en": "English",
    "es": "Spanish",
    "et": "Estonian",
    "fi": "Finnish",
    "fr": "French",
    "he": "Hebrew",
    "hi": "Hindi",
    "hr": "Croatian",
    "hu": "Hungarian",
    "id": "Indonesian",
    "it": "Italian",
    "iw": "Hebrew",  # old code
    "ja": "Japanese",
    "ko": "Korean",
    "lt": "Lithuanian",
    "lv": "Latvian",
    "nl": "Dutch",
    "no": "Norwegian",
    "pl": "Polish",
    "pt": "Portuguese",
    "ro": "Romanian",
    "ru": "Russian",
    "sk": "Slovak",
    "sl": "Slovenian",
    "sr": "Serbian",
    "sv": "Swedish",
    "sw": "Swahili",
    "th": "Thai",
    "tr": "Turkish",
    "uk": "Ukrainian",
    "vi": "Vietnamese",
    "zh": "Chinese",
    "zh-CN": "Chinese (Simplified)",
    "zh-TW": "Chinese (Traditional)",
}

country_code_to_language_code = {
    "AD": ["en"],
    "AE": ["ar"],
    "AF": ["en"],
    "AG": ["en"],
    "AI": ["en"],
    "AL": ["en"],
    "AM": ["en"],
    "AO": ["pt"],
    "AQ": ["en"],
    "AR": ["es"],
    "AS": ["en"],
    "AT": ["de"],
    "AU": ["en"],
    "AW": ["nl"],
    "AX": ["sv"],
    "AZ": ["en"],
    "BA": ["hr", "sr"],
    "BB": ["en"],
    "BD": ["bn"],
    "BE": ["de", "fr", "nl"],
    "BF": ["fr"],
    "BG": ["bg"],
    "BH": ["ar"],
    "BI": ["en", "fr"],
    "BJ": ["fr"],
    "BL": ["fr"],
    "BM": ["en"],
    "BN": ["en"],
    "BO": ["es"],
    "BQ": ["nl"],
    "BR": ["pt"],
    "BS": ["en"],
    "BT": ["en"],
    "BV": ["no"],
    "BW": ["en"],
    "BY": ["ru"],
    "BZ": ["en"],
    "CA": ["en", "fr"],
    "CC": ["en"],
    "CD": ["fr"],
    "CF": ["fr"],
    "CG": ["fr"],
    "CH": ["de", "fr", "it"],
    "CI": ["fr"],
    "CK": ["en"],
    "CL": ["es"],
    "CM": ["en", "fr"],
    "CN": ["zh"],
    "CO": ["es"],
    "CR": ["es"],
    "CU": ["es"],
    "CV": ["pt"],
    "CW": ["en", "nl"],
    "CX": ["en", "zh"],
    "CY": ["el", "tr"],
    "CZ": ["cs", "sk"],
    "DE": ["de"],
    "DJ": ["ar", "fr"],
    "DK": ["da"],
    "DM": ["en"],
    "DO": ["es"],
    "DZ": ["ar"],
    "EC": ["es"],
    "EE": ["et"],
    "EG": ["ar"],
    "EH": ["ar"],
    "ER": ["en"],
    "ES": ["es"],
    "ET": ["en"],
    "FI": ["fi", "sv"],
    "FJ": ["en"],
    "FK": ["en"],
    "FM": ["en"],
    "FO": ["da"],
    "FR": ["fr"],
    "GA": ["fr"],
    "GB": ["en"],
    "GD": ["en"],
    "GE": ["en"],
    "GF": ["fr"],
    "GG": ["en", "fr"],
    "GH": ["en"],
    "GI": ["en"],
    "GL": ["en"],
    "GM": ["en"],
    "GN": ["fr"],
    "GP": ["fr"],
    "GQ": ["es", "fr", "pt"],
    "GR": ["el"],
    "GS": ["en"],
    "GT": ["es"],
    "GU": ["en"],
    "GW": ["pt"],
    "GY": ["en"],
    "HK": ["en", "zh"],
    "HM": ["en"],
    "HN": ["es"],
    "HR": ["hr"],
    "HT": ["fr"],
    "HU": ["hu"],
    "ID": ["id"],
    "IE": ["en"],
    "IL": ["he"],
    "IM": ["en"],
    "IN": ["en", "hi"],
    "IO": ["en"],
    "IQ": ["ar"],
    "IR": ["en"],
    "IS": ["en"],
    "IT": ["it"],
    "JE": ["en"],
    "JM": ["en"],
    "JO": ["ar"],
    "JP": ["ja"],
    "KE": ["en", "sw"],
    "KG": ["ru"],
    "KH": ["en"],
    "KI": ["en"],
    "KM": ["ar", "fr"],
    "KN": ["en"],
    "KP": ["ko"],
    "KR": ["ko"],
    "KW": ["ar"],
    "KY": ["en"],
    "KZ": ["ru"],
    "LA": ["en"],
    "LB": ["ar"],
    "LC": ["en"],
    "LI": ["de"],
    "LK": ["en"],
    "LR": ["en"],
    "LS": ["en"],
    "LT": ["lt"],
    "LU": ["de", "fr"],
    "LV": ["lv"],
    "LY": ["ar"],
    "MA": ["ar"],
    "MC": ["fr"],
    "MD": ["ro"],
    "ME": ["en"],
    "MF": ["fr"],
    "MG": ["fr"],
    "MH": ["en"],
    "MK": ["en"],
    "ML": ["fr"],
    "MM": ["en"],
    "MN": ["en"],
    "MO": ["pt", "zh"],
    "MP": ["en"],
    "MQ": ["fr"],
    "MR": ["ar"],
    "MS": ["en"],
    "MT": ["en"],
    "MU": ["en"],
    "MV": ["en"],
    "MW": ["en"],
    "MX": ["es"],
    "MY": ["en"],
    "MZ": ["pt"],
    "NA": ["en"],
    "NC": ["fr"],
    "NE": ["fr"],
    "NF": ["en"],
    "NG": ["en"],
    "NI": ["es"],
    "NL": ["nl"],
    "NO": ["no"],
    "NP": ["en"],
    "NR": ["en"],
    "NU": ["en"],
    "NZ": ["en"],
    "OM": ["ar"],
    "PA": ["es"],
    "PE": ["es"],
    "PF": ["fr"],
    "PG": ["en"],
    "PH": ["en"],
    "PK": ["en"],
    "PL": ["pl"],
    "PM": ["fr"],
    "PN": ["en"],
    "PR": ["en", "es"],
    "PS": ["ar"],
    "PT": ["pt"],
    "PW": ["en"],
    "PY": ["es"],
    "QA": ["ar"],
    "RE": ["fr"],
    "RO": ["ro"],
    "RS": ["sr"],
    "RU": ["ru"],
    "RW": ["en", "fr", "sw"],
    "SA": ["ar"],
    "SB": ["en"],
    "SC": ["en", "fr"],
    "SD": ["ar", "en"],
    "SE": ["sv"],
    "SG": ["en", "zh"],
    "SH": ["en"],
    "SI": ["sl"],
    "SJ": ["no"],
    "SK": ["sk"],
    "SL": ["en"],
    "SM": ["it"],
    "SN": ["fr"],
    "SO": ["ar"],
    "SR": ["nl"],
    "SS": ["en"],
    "ST": ["pt"],
    "SV": ["es"],
    "SX": ["en", "nl"],
    "SY": ["ar"],
    "SZ": ["en"],
    "TC": ["en"],
    "TD": ["ar", "fr"],
    "TF": ["fr"],
    "TG": ["fr"],
    "TH": ["th"],
    "TJ": ["en"],
    "TK": ["en"],
    "TL": ["pt"],
    "TM": ["en"],
    "TN": ["ar"],
    "TO": ["en"],
    "TR": ["tr"],
    "TT": ["en"],
    "TV": ["en"],
    "TW": ["zh"],
    "TZ": ["en"],
    "UA": ["uk"],
    "UG": ["en", "sw"],
    "UM": ["en"],
    "US": ["en"],
    "UY": ["es"],
    "UZ": ["en"],
    "VA": ["it"],
    "VC": ["en"],
    "VE": ["es"],
    "VG": ["en"],
    "VI": ["en"],
    "VN": ["vi"],
    "VU": ["en", "fr"],
    "WF": ["fr"],
    "WS": ["en"],
    "YE": ["ar"],
    "YT": ["fr"],
    "ZA": ["en"],
    "ZM": ["en"],
    "ZW": ["en"],
    "OTHER": ["en"],
}

language_codes_knowrecall = [
    "ar", "de", "el", "en", "es", "fr", "he", "it",
    "ja", "ko", "pt", "ru", "sr", "th", "zh",
]
language_codes_visrecall = ["ar", "de", "en", "es", "fr", "it", "ja", "pt", "zh"]
